### PR TITLE
Update to SDK 0.6.5

### PR DESCRIPTION
**Pull request by TheBikingViking**
Update to the latest Lookback SDK

### CODE REVIEW

**Comment by TheBikingViking** [comment]
Any thoughts on this @nevyn ?

**Comment by nevyn** [comment]
23 days? I'm so very sorry for my slow response :(

Ok, so:

*  0.8.1 bundles resources in a different manner, so I had to change the xml a little; now it's working.
* Sorry, I reverted your change to default to HD. I would hate for people accidentally getting rejected in appstore review because this plugin suddenly became un-safe.
* I've changed the setupWithAppToken code to check if it's being called twice, and not crash if that's the case. It will still log to the console. There's no way to check if Lookback has been setup, except by keeping track of it in a variable like I'm doing in CDVLookback.m:4.

Thanks for the help!! This has now been pushed upstream with a manual merge.

**Comment by TheBikingViking** [comment]
Thanks, and thanks for the additional fixes. Noticed the 0.8.1 bundle resources issue today, but great to see you already got it covered :) And yes, reverting back to non-HD is best for the core plugin.

**Comment by littke** [comment]
@TheBikingViking, Jesper, thanks for this PR, we appreciate it!

**Pull request merged**
