### PR TITLE
Lookback SDK upgrade to 1.1.4

### PR DESCRIPTION
**Pull request by maksymilian-majer**
We were exepriencing some issued and crashes with the 1.0.2 version of Lookback SDK, so I upgraded the SDK to 1.1.4 and renamed the plugin name to match cordova plugins naming convention.

### CODE REVIEW

**Comment by littke** [comment]
Nice!

cc @nevyn

**Comment by dvicory** [comment]
Would really like this!

**Comment by nevyn** [comment]
Thank you very much, this is perfect @maksymilian-majer! Didn't even require any API changes, nice :)

**Comment by littke** [comment]
:+1:

**Comment by maksymilian-majer** [comment]
@nevyn You're welcome! Lookback is such a great tool, that I hope I can contribute more :)

**Pull request merged**
